### ISSUE TITLE
consider using @npmcli/arborist for navigating the dependency tree

### ISSUE THREAD

**Issue by mvayngrib** [tmorell/license-compliance#221]
**Is your feature request related to a problem? Please describe.**

there's no problem, but i noticed [arborist](https://www.npmjs.com/package/@npmcli/arborist) being used in a similar project, and thought u might not be aware of it

**Describe the solution you'd like**

use arborist rather than reimplement that functionality here

just an idea!

**Comment by tmorell** [comment]
Thanks for sharing.
