### ISSUE TITLE
Configuration pattern

### ISSUE THREAD

**Issue by flo-sch** [tmorell/license-compliance#56]
Hi,

I am just discovering this promising package, while benchmarking different tools we may use for such compliance needs, so far it looks quite simple **to use** yet powerful!
Just out of curiosity, would you consider relying on a configuration loader, especially supporting configuration extension?

**Is your feature request related to a problem? Please describe.**

My current main use-case is about "organization-level" compliance: maintaining a list of allowed licenses in each CI/CD pipelines of (potentially a lot of) repositories can become quite a burden.
Being able to inherit a shareable, centralized compliance policy to combine such a tool would be absolutely amazing.

One example coming to my mind would be eslint for instance:
https://eslint.org/docs/developer-guide/shareable-configs

**Describe the solution you'd like**

On a consumption level, basically to be able to provide the source of "allowed" (or potentially "denied" licenses in the future?) from a centralised source:

```json
{
  "license-compliance": {
    "extends": "@some-central-scope/centralized-licenses-policy"
  }
}
```

**Describe alternatives you've considered**

To my understanding, there are packages that can help with that, even though I haven't digged into the details of configuration extension (my main use-case here):
- https://github.com/davidtheclark/cosmiconfig
- https://github.com/dominictarr/rc

**Additional context**

If you find that interesting, I could contribute with a PR, potentially just need some owner guidance for implementation details?

**Comment by tmorell** [comment]
@flo-sch  This is a good suggestion. I have a PR in WIP at https://github.com/tmorell/license-compliance/pull/63
The approach is to have **main()** get the configuration from **getConfiguration()** instead of doing it directly from the command line. **getConfiguration()** merges settings from inline configuration, extended configuration, and the command line.
```javascript
const configuration = Object.assign(configExtended, configInline, configCommand);
```
Still need to remove all unsafe declarations and add validation.

**Comment by flo-sch** [comment]
I thought cosmiconfig allowed extension natively, sorry for the misleading example 🙈 
PR looks good though, I have some work as well to ensure `getConfiguration` always return a valid, complete `Configuration` interface to rely on internally, let me know what you think?

Just a small disclaimer as well, unit tests pass locally but I have not been able to end-to-end test it, not sure how you do it on your end?

**Comment by tmorell** [comment]
@flo-sch Thank you for the PR. There were some very welcome changes. Passing the configuration as a parameter removed a global dependency and simplified the unit testing.
I have merged your PR with #63. Some additional changes:
## configuration.ts
All methods rely on the properties being undefined, so checks like this will fail:
```typescript
    if (!configuration.allow) {
        return [];
    }
```

Using this instead:
```typescript
return {
    ...configuration.allow && { allow: configuration.allow },
    ...configuration.development && { development: configuration.development },
    ...configuration.direct && { direct: configuration.direct },
    ...configuration.exclude && { exclude: configuration.exclude },
    ...configuration.production && { production: configuration.production },
    format: toPascal(configuration.format) as Formatter || Formatter.text,
    report: toPascal(configuration.report) as Report || Report.summary
};
```
Commit: c716bf0b89a6cf834b24d733f185eff4f78b7a50

## program.ts
Removed default values for **format** and **report**. Program was overwriting the rc or extended configuration, even if not arguments were defined.

## Testing
I will work tonight unit testing the configuration. Overrides must go from command line -> rc file -> extended configuration.

For end to end test, you can run:
```batch
npm run build && node lib/index.js {arguments}
```
It will evaluate the packages in this solution.

**Comment by flo-sch** [comment]
Alright, I had doubts about default values indeed, thanks for clarifying :)

I thought all methods not necessarily needed all keys to be defined, and I think it is a good thing that `getConfiguration()` does return a complete, reliable `Configuration` interface anyway!

I also like the order `CLI` > `inline` > `extended`, allowing to opt-in inline for specific options, and if needed, override them with CLI like in a CI/CD pipeline... Looks great 💪

**Comment by flo-sch** [comment]
Just one thing I was not sure about is the extension loader: `await explorer.load(`node_modules/${extendsPath}/index.js`);`, that requires an index, which is obviously quite common, but I was wondering if there was a way to rely on native node resolution instead... I will try to figure that out, no big deal anyway!

**Comment by tmorell** [comment]
I decided to go with your suggestion and return a complete configuration: 14c1a835ef6fec17ee5b45edb1bcc3f30b4bc3ca
Also, I added validation with Joi: 937f84c66afce58b6e011aa3b9ff5480481bc18e
There is some more work, like extracting the license validation from `program.ts`, and adding it to Joi, but I think it is good for the moment.
Let me know if you have any feedback. If everything is OK, I will publish the new version.

**Comment by tmorell** [comment]
@flo-sch  The new package, 1.1.0, has been published to npm.
Thank you for the great idea and PR.

**Comment by flo-sch** [comment]
Great job! Sorry was a bit busy those past 2 days, but looking forward to try that out :)

So far the inline config seems to work, I will try to extended one next week!

**Comment by flo-sch** [comment]
Just to confirm, `extends` work like a charm :)

I just had a few troubles with the `--report` flag option being ignored before realizing it is hardcoded when `allow` is also provided:
https://github.com/tmorell/license-compliance/blob/master/src/main.ts#L32

Is it intentional to use `invalid` here instead of the configuration report argument?

**Comment by tmorell** [comment]
Good point. Actually the `invalid` report type is not needed.
If the allowed licenses check is not met, you should be able to get a `summary` or `detailed` report.
I will fix in a couple days.
