### ISSUE TITLE
Feature Request: XUnit reporter (or facilitated integration?)

### ISSUE THREAD

**Issue by flo-sch** [tmorell/license-compliance#70]
Hi,

While playing around with Bitbucket Pipelines (quite sweet now with the extendable configuration, thanks a lot for that!!)
I wrote a small script parsing `license-compliance` generated output (json) and transforming it a XUnit (XML based) report.

Is that something you think could be interesting to package here?

PS: obviously ready to contribute on that, just wanted to hear your thoughts (& guidance if you think we should proceed with it)

**Is your feature request related to a problem? Please describe.**

Bitbucket Pipelines can [show contextual informations](https://support.atlassian.com/bitbucket-cloud/docs/test-reporting-in-pipelines/) about problems in CI steps if reports are emitted in that XUnit format.

I just had to tweak a small CI step to make it work with license-compliance:
- first ensure `license-compliance` does not break the build (even with non-compliant packages detected)
- then parse that report, transforms it to XUnit
- terminates the process with `process.exitCode = 1` (if some packages are invalid)

My simplified package.json looks like:

```json
{
  "scripts": {
    "license-compliance": "^1.1.0",
    "xml": "^1.0.1"
  },
  "devDependencies": {
    "licenses:report": "license-compliance --format json --report detailed > test-reports/license-compliance.json",
    "licenses:report-xunit": "{my own script using 'xml'} --source-file test-reports/license-compliance.json --target-file test-reports/license-compliance.xml"
  }
}
```

My CI pipeline looks like:

```yml
# bitbucket-pipelines.yml
definitions:
  steps:
    - step: &audit-licenses
        name: Audit licenses
        script:
          # Install dependencies
          - yarn install --frozen-lockfile
          # Audit all packages
          - |
            set +e
            yarn run licenses:report
            set -e
          - yarn run licenses:report-xunit
```

**Describe the solution you'd like**

The way I see it, one option would be to build a new `xunit` reporter.

That format is XML based and uses specific nodes, as well as optional attributes (see sample below).
Using [xml](https://www.npmjs.com/package/xml) for instance, the process is quite straightforward.

Pros: in bitbucket-pipelines, a single script could directly generate the report, without the need to handle those `set +e` or run another process right after.

Cons: this (probably?) means a new dependency to output in XML format, and one more reporter to maintain.

**Describe alternatives you've considered**

I have been thinking about 3 alternatives (without building such reporter) that could still make such an integration even easier in an external script / package:

1. an opt-in flag to avoid breaking the build, ensuring `process.exitCode = 0` even if some problems are identified (simplify a bit the CI process)
2. have a way to invoke `license-compliance` as a module on top of a CLI tool: that would basically means:
  - exporting the external API used in `index.ts`
  - consume it in `bin/cli.js` instead
  - maybe tweak the package.json fields (not even sure if we need actually)
3. a way to get insights in reports such as number of audited packages, number of valid & invalid licenses etc. (100% "cherry on the cake" bonus)

**Additional context**

The equivalent of the following JSON sample:

```json
[
  {
    "license": "Unlicense",
    "licenseFile": "node_modules/test-1/LICENSE",
    "name": "test-1",
    "path": "node_modules/test-1",
    "repository": "test-1",
    "version": "1.2.0"
  },
  {
    "license": "Unlicense",
    "licenseFile": "node_modules/test-2/LICENSE",
    "name": "test-2",
    "path": "node_modules/test-2",
    "repository": "test-2",
    "version": "2.5.1"
  },
  {
    "license": "GPL-3.0",
    "licenseFile": "node_modules/test-3/LICENSE",
    "name": "test-3",
    "path": "node_modules/test-3",
    "repository": "test-3",
    "version": "0.1.4-alpha.3"
  }
]
```

Would be

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="License Compliance" tests="3" errors="0" failures="3">
  <testsuite name="Unlicense" tests="2" errors="0" failures="2">
    <testcase name="test-1@1.2.0" path="node_modules/test-1">
      <failure type="License Compliance Error">Package &quot;test-1@1.2.0&quot; uses non compliant license &quot;Unlicense&quot;</failure>
    </testcase>
    <testcase name="test-2@2.5.1" path="node_modules/test-2">
      <failure type="License Compliance Error">Package &quot;test-2@2.5.1&quot; uses non compliant license &quot;Unlicense&quot;</failure>
    </testcase>
  </testsuite>
  <testsuite name="GPL-3.0" tests="1" errors="0" failures="1">
    <testcase name="test-3@0.1.4-alpha.3" path="node_modules/test-3">
      <failure type="License Compliance Error">Package &quot;test-3@0.1.4-alpha.3&quot; uses non compliant license &quot;GPL-3.0&quot;</failure>
    </testcase>
  </testsuite>
</testsuites>
```

And just to illustrate how it looks in Bitbucket Pipelines (with actual packages):

![license-compliance-bitbucket-pipelines](https://user-images.githubusercontent.com/1577155/112040273-4dd8f300-8b45-11eb-873b-0ec093e48064.png)

**Comment by tmorell** [comment]
I think it will be a good addition and having a new formatter to maintain is not a burden.
A PR is welcome. I just need a day or so to close #72, which might impact it. I need to migrate to Github actions since I ran out of credits in Travis :(.

**Comment by flo-sch** [comment]
Alright sounds good :)

I have a bit experience with GA, but 0 with Travis, is there any way I can help perhaps?

**Comment by tmorell** [comment]
I finished the PR for #72. You should be able to work on the XUnit reporter.

**Comment by tmorell** [comment]
@flo-sch  Thank you for the PR.
Package 1.2.0 is available @ npm.

**Comment by tmorell** [comment]
@flo-sch I noticed that when querying packages, the output of the XML indicates `failures`.
For example:
```bash
 npx license-compliance -q "MIT" -f xunit
```

The output shows `failures="1"`.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="License Compliance" tests="1" errors="0" failures="1">
  <testsuite name="MIT" tests="1" errors="0" failures="1">
    <testcase name="MIT">
      <failure type="License Compliance Error">332 packages use non compliant license "MIT"</failure>
    </testcase>
  </testsuite>
</testsuites>
```
Is this the expected behavior for `xunit`? What is the difference between `errors` and `failures`?
It is assuming that the count is errors.

`--query / -q` was recently added, but the old behavior of just calling the CLI without `--allow` would just list the packages' license.
For erxample:
```bash
npx license-compliance -f text
```

```
Licenses
├─ (BSD-2-Clause OR MIT OR Apache-2.0): 1
├─ (MIT AND CC-BY-3.0): 1
├─ (MIT OR CC0-1.0): 1
├─ Apache-2.0: 21
├─ BlueOak-1.0.0: 8
├─ BSD-2-Clause: 13
├─ BSD-3-Clause: 21
├─ CC-BY-3.0: 1
├─ CC0-1.0: 2
├─ ISC: 34
├─ MIT: 332
├─ MPL-2.0: 1
├─ Python-2.0: 1
└─ UNKNOWN: 2

exit code `0`
```
 
With `xunit`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="License Compliance" tests="14" errors="0" failures="14">
  <testsuite name="(BSD-2-Clause OR MIT OR Apache-2.0)" tests="1" errors="0" failures="1">
    <testcase name="(BSD-2-Clause OR MIT OR Apache-2.0)">
      <failure type="License Compliance Error">1 package use non compliant license "(BSD-2-Clause OR MIT OR Apache-2.0)"</failure>
    </testcase>
  </testsuite>
  <testsuite name="(MIT AND CC-BY-3.0)" tests="1" errors="0" failures="1">
    <testcase name="(MIT AND CC-BY-3.0)">
      <failure type="License Compliance Error">1 package use non compliant license "(MIT AND CC-BY-3.0)"</failure>
    </testcase>
  </testsuite>
  <testsuite name="(MIT OR CC0-1.0)" tests="1" errors="0" failures="1">
    <testcase name="(MIT OR CC0-1.0)">
      <failure type="License Compliance Error">1 package use non compliant license "(MIT OR CC0-1.0)"</failure>
    </testcase>
  </testsuite>
  <testsuite name="Apache-2.0" tests="1" errors="0" failures="1">
    <testcase name="Apache-2.0">
      <failure type="License Compliance Error">21 packages use non compliant license "Apache-2.0"</failure>
    </testcase>
  </testsuite>
  <testsuite name="BlueOak-1.0.0" tests="1" errors="0" failures="1">
    <testcase name="BlueOak-1.0.0">
      <failure type="License Compliance Error">8 packages use non compliant license "BlueOak-1.0.0"</failure>
    </testcase>
  </testsuite>
  <testsuite name="BSD-2-Clause" tests="1" errors="0" failures="1">
    <testcase name="BSD-2-Clause">
      <failure type="License Compliance Error">13 packages use non compliant license "BSD-2-Clause"</failure>
    </testcase>
  </testsuite>
  <testsuite name="BSD-3-Clause" tests="1" errors="0" failures="1">
    <testcase name="BSD-3-Clause">
      <failure type="License Compliance Error">21 packages use non compliant license "BSD-3-Clause"</failure>
    </testcase>
  </testsuite>
  <testsuite name="CC-BY-3.0" tests="1" errors="0" failures="1">
    <testcase name="CC-BY-3.0">
      <failure type="License Compliance Error">1 package use non compliant license "CC-BY-3.0"</failure>
    </testcase>
  </testsuite>
  <testsuite name="CC0-1.0" tests="1" errors="0" failures="1">
    <testcase name="CC0-1.0">
      <failure type="License Compliance Error">2 packages use non compliant license "CC0-1.0"</failure>
    </testcase>
  </testsuite>
  <testsuite name="ISC" tests="1" errors="0" failures="1">
    <testcase name="ISC">
      <failure type="License Compliance Error">34 packages use non compliant license "ISC"</failure>
    </testcase>
  </testsuite>
  <testsuite name="MIT" tests="1" errors="0" failures="1">
    <testcase name="MIT">
      <failure type="License Compliance Error">332 packages use non compliant license "MIT"</failure>
    </testcase>
  </testsuite>
  <testsuite name="MPL-2.0" tests="1" errors="0" failures="1">
    <testcase name="MPL-2.0">
      <failure type="License Compliance Error">1 package use non compliant license "MPL-2.0"</failure>
    </testcase>
  </testsuite>
  <testsuite name="Python-2.0" tests="1" errors="0" failures="1">
    <testcase name="Python-2.0">
      <failure type="License Compliance Error">1 package use non compliant license "Python-2.0"</failure>
    </testcase>
  </testsuite>
  <testsuite name="UNKNOWN" tests="1" errors="0" failures="1">
    <testcase name="UNKNOWN">
      <failure type="License Compliance Error">2 packages use non compliant license "UNKNOWN"</failure>
    </testcase>
  </testsuite>
</testsuites>
```

BTW, I am migrating `xmlbuilder` to `xmlbuilder2` here: https://github.com/tmorell/license-compliance/pull/308

**Comment by flo-sch** [comment]
Hey @tmorell, while I cannot find any official specification to link sadly, from what I recall, they are meant to indicate different things:

- "failures" indicates that the test executes but results in failing assertions
- "errors" indicates that the test ran into an error while executing (uncaught exception or similar)

I have not work with bitbucket pipelines in a while, I am not fully sure if errors and failures would be shown differently in their UI.

> the old behavior of just calling the CLI without --allow would just list the packages' license

Are you saying that when using xunit without allow, the result shows failures? That seems like a bug to me, if an empty "allow" option is meant to allow all licences?
