### ISSUE TITLE
False negative messages in report (xunit)

### ISSUE THREAD

**Issue by flo-sch** [tmorell/license-compliance#85]
Hi Teo,

I have been playing around with v1.2.0, working well so far, except I realize I only considered the `--allow` scenario when building the xunit reporter ([especially the content of the messages](https://github.com/tmorell/license-compliance/blob/master/src/formatters/xunit.ts#L70)), and there are 2 cases where those messages are a bit confusing at the moment (false negative)

**Is your feature request related to a problem? Please describe.**

1. When [no package can be identified](https://github.com/tmorell/license-compliance/blob/master/src/main.ts#L22) (e.g. running with `--production` but there is no `dependencies`), the command returns with an error exit code. Is that intentional?
I am thinking that if I have 0 dependency, then I probably have no compliance issue, but perhaps the behavior could depend whether `--allow` is also provided or not?
(I know it may feel a bit weird to run an audit if there is nothing to audit. But in my scenario, the person setting up the audit may not be a direct project/package maintainer, and might want to ensure the audit will run in the future when dependencies start to be added)
2. If `--allow` is provided but no invalid package is found, the reporter [process all packages](https://github.com/tmorell/license-compliance/blob/master/src/main.ts#L32). This is probably intentional, my problem is that the xunit reporter consider those to be "non-compliant".

**Describe the solution you'd like**

1. just return `true` if 0 dependency is found, so the command exit with a success code (at least when `--allow` is provided?). Perhaps also notify it might be a typo? (not sure how such notification would look in different formats though)

2. I was thinking we could either:
    - forward the configuration to "process", in order to have dynamic messages in for instance the xunit reporter
    - or always process the invalid packages (even an empty array) when `--allow` is provided

**Additional context**
Ready to contribute again of course, just want to hear your thoughts first :)

**Comment by tmorell** [comment]
Hi @flo-sch ,
"Just return true if 0 dependency is found". Totally agree. This should be regardless of `--allow`.

Also, if `--allow` is specified, probably we should skip the report and just return with exit code `0`.
The only moment I would not use `--allow` is to inspect the packages, and that will be at the console using `npx`.

Do these address the problem that you are having? 
Please feel free to put a PR.

**Comment by flo-sch** [comment]
Great, I think those would cover it fully, I will create a PR :)

The only tiny edge-case I can see is if you use `--report xunit` without `--allow`, the messages would still say "non compliant", but even me cannot see it as an actual use-case, XML is too verbose for summaries and I would not even consider it if it was not for Bitbucket

**Comment by tmorell** [comment]
@flo-sch Package 1.2.1 is published. Thank you for the fix.

**Comment by flo-sch** [comment]
Amazing, thanks for the quick release again :)
